### ISSUE TITLE
Clustering implementation

### ISSUE THREAD

**Issue by jiayily** [YevgeniyEngineer/LiDAR-Processing#12]
"To perform clustering on segmented LiDAR points I used the adaptation of [Fast Euclidean Clustering](https://arxiv.org/abs/2208.07678)."

It seems that after the adaptation, the algorithm is totally different from [the official implementation](https://github.com/YizhenLAO/FEC). Does the adapted one still get a good real-time performance?

**Comment by YevgeniyEngineer** [comment]
Depending on the cluster quality parameter algorithm can be tuned to meet real time performance constraints. I am aware it is deviating from the original implementation, I mostly used breadth first search for cluster expansion as a reference, but haven't cross compared against the official implementation. I have verified that the algorithm is real-time compliant and has below 20ms execution time using 0.5 cluster quality testing with Velodyne data from Kitti dataset (roughly 125k points per frame at 10Hz). If in doubt, I suggest you test execution time on your own hardware. If extreme performance is needed, my Lidar Processing Pipeline V2 has below 10ms clustering time, but it is based on the grid based approach instead.

**Comment by jiayily** [comment]
Thanks so much. What does the cluster quality parameter mean actually?

**Comment by YevgeniyEngineer** [comment]
When neighbours of the seed point are found, if the points are within the scaled distance from the core point, they will not be used for cluster expansion. The scaled distance is calculated as (1-cluster quality) * distance. This is just a trick to significantly minimise the number of calculation without compromising cluster shapes. You can think of it this way - if I search for neighbours around the seed point, if the neighbours are located very close to the seed point, I can assume that it is irrelevant to use them for cluster expansion, because the neighbours of the neighbours are likely within the distance threshold from the seed.

**Comment by jiayily** [comment]
Got it. Thanks for your detailed explanation.
